apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: graphdb
  name: graphdb
spec:
  ports:
  - name: "7474"
    port: 7474
    targetPort: 7474
  - name: "7687"
    port: 7687
    targetPort: 7687
  - name: "2004"
    port: 2004
    targetPort: 2004
  selector:
    io.kompose.service: graphdb
status:
  loadBalancer: {}
