version: '3'
services:
  graphdb:
    image: neo4j:3.4-enterprise
    container_name: hawk-graphdb
    ports:
      - "7474:7474"
      - "7687:7687"
      - "2004:2004"
    volumes:
      - ./database/neo4j/plugins:/plugins
      - $HOME/neo4j/hawk/data:/data
      - $HOME/neo4j/hawk/logs:/logs
    environment:
      NEO4J_AUTH: neo4j/123456
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    networks:
      - hawk-network

  api:
    container_name: hawk-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    env_file:
      - api.env
    depends_on:
      - graphdb
    networks:
      - hawk-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: hawk-swagger
    ports:
      - "5001:8080"
    environment:
      API_URL: http://localhost:5000/swagger/v1/swagger.json
    networks:
      - hawk-network

  prometheus:
    image: prom/prometheus:v2.7.2
    container_name: hawk-prometheus
    ports:
      - "5002:9090"
    volumes:
      - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - api
    networks:
      - hawk-network

  grafana:
    image: grafana/grafana:5.4.3
    container_name: hawk-grafana
    ports:
      - "5003:3000"
    env_file:
      - ./monitor/grafana/grafana.env
    volumes:
      - ./monitor/grafana/config.ini:/etc/grafana/config.ini
      - ./monitor/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitor/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - hawk-network

networks:
  hawk-network:
    driver: bridge
