apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 9090
  selector:
    io.kompose.service: prometheus
status:
  loadBalancer: {}
