apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: swagger
  name: swagger
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: swagger
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://localhost:5000/swagger/v1/swagger.json
        image: swaggerapi/swagger-ui
        name: hawk-swagger
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
