apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose.exe convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 3000
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
